### PR TITLE
Kml2.2

### PR DESCRIPTION
**Pull request by annerajb**
Ok this is the real deal I made a branch for it

### CODE REVIEW

**Comment by apps4av** [comment]
We are going to test these in flight on Friday then merge on the weekend if they work. Regarding continuous integration, do you have plans to make some tests? Otherwise we tightly control the quality of merges and having CI is probably not that useful without tests.

**Comment by annerajb** [comment]
Yes
I plan down the line to add test. Probably for the notification feature I
am working to make sure the intent action work.

**Comment by apps4av** [comment]
Suggest adding author to authors list on top of file.

**Comment by apps4av** [comment]
There are issues with this new format as it is not working properly with google earth. Previously, lines in 3D were shown for the path, but now google earth shows just points. Please check.

**Pull request merged**
