### PR TITLE
testing out revamped ui

### PR DESCRIPTION
**Pull request by xargsgrep**
Firstly, let me be clear that this pull request is **NOT** a merge request. This is just a sandbox branch where I have been playing around with a revamped UI. I just wanted to put it out there because I was hoping to get some feedback from others to see if there is any interest in something like this - if not then I won't continue working on it. You can build the branch and play around with it on a device and also see the attached screenshots below. Needless to say, there are plenty of issues and this would require an **extensive** amount of testing if there is any interest in moving forward with this.

### Changes
- Converted all core activities to fragments to allow for more flexible UI
- Added NavigationView for left side navigation drawer
- Added Toolbar for top action bar with options menu
  - Chart/Layer selection can be done directly from action bar
  - Removed map menu button and moved everything to options menu 
- Replaced bottom tab scroll bar with TabLayout (this can be disabled if user only wants to use nav drawer)
- Uses appcompat-v7 library so technically, this should all work on a device running API 9 which is the minSdkVersion for the project.
- Material design (for new stuff)
- Replaced all Toasts with Snackbars 
- Added a test split view for displaying views side by side (map view with plates view). This doesn't really work, it's there mostly as a demo

### Known Issues
- Fragments are always replaced, so they are created from scratch whenever you switch to a different view and back (ie state is lost) - this shouldn't be difficult to fix
- When swiping open the nav drawer on the map view, the plane icon disappears until the map is touched again
- Night mode needs to be implemented again
- The theme/colors/styling can be changed easily and I mostly picked some random values as I'm not really a UI person
- I'm sure a ton of others - I am out of town these days and I can't test in flight

device-2016-06-26-155339
device-2016-06-26-155411
device-2016-06-26-155457
device-2016-06-26-155531
device-2016-06-26-155733
device-2016-06-26-155837
device-2016-06-26-160044
device-2016-06-26-160142
device-2016-06-26-160235

### CODE REVIEW

**Comment by annerajb** [comment]
Looks pretty good I was thinking long time ago of doing something like this. Working on other projects now..

What resolution are those screenshots taken as? They look like a tablet/note device.
Wonder what would it look on a regular phone like a lg g2,lg g3, or nexus 5x.

**Comment by xargsgrep** [comment]
Screenshots are from my Nexus 6P which is 1440 x 2560, so yes, pretty high res. I briefly tested on a Nexus 4 emulator and it still looked ok.

**Comment by r-oleary** [comment]
@xargsgrep i've created a new branch on this repo called "ui_revamp" based on your branch. This will allow us to have a branch on this repo that people can play with. Please make any changes to this stuff as PRs to that branch for the foreseeable future. 

I recommend we take this "discussion" to Groups, so that it is more persistent and not tied to code processes. There is a dev group and a public group - since this is so far-reaching, recommend we use the public group: https://groups.google.com/forum/#!forum/apps4av-forum

**Comment by apps4av** [comment]
I suggest merging new UI, new touch, and shaded areas to one branch on
apps4av main repo. roleary has a branch there already, or I can create a
new one. I will add xargsgrep to main repo so he can directly change the
new branch without hassle of maintaining and merging his own repo.
Once this branch is ready with the above proposed changes, we will make a
beta and put it on the group and will ask people to comment and report bugs.
The new UI looks great. Testing it will be through users using a beta or
through  google play beta release.
We will also do 256 pixel tiles here. So a lot to test but very excited.
Thanks!

**Comment by apps4av** [comment]
Sounds like a plan. @xargs - can you duplicate your first comment on this
PR as a new thread in the Avare Dev chat you were just added to? Let's take
this discussion there. Thanks.

**Comment by xargsgrep** [comment]
Yup sounds good, will do thanks!

**Comment by r-oleary** [comment]
Closing this PR for now. Part of ui_revamp effort

**Pull request closed without merging**
