### PR TITLE
Weather briefing - fix html for proper rendering of sign plus (Heavy)

### PR DESCRIPTION
**Pull request by pasniak**
...which was swallowed (!) and proper rendering in Firefox (not closed <font> tags cause HTML engine to stop rendering (see: https://support.mozilla.org/en-US/questions/846246 ) 

#274

### CODE REVIEW

**Comment by apps4av** [comment]
This has broken the build 7.7.1 weather briefing as reported by users.
screenshot_20170721-074547

**Comment by apps4av** [comment]
Comment:
I create a flight plan and go to the bottom and click "Get Briefing" I get the pop up to "get latest plan briefing from internet?" and click ok. I immediately get the attached screenshot. I have uninstalled/reinstalled Avare, Factory Reset the device, and tried every thing simple I can think of. 

All other functions of the app operate as expected and it is a great app. 

Hardware is a Samsung Tab A Model SM-T350 running Android Version 6.0.1

**Comment by pasniak** [comment]
No problems here (I am on upstream/master with AHRS changes applied) .  I will try official build after I come back from flying tomorrow.
screenshot_2017-07-21-22-04-56

Could you attach the generated html file? in storage/emulated/0/Download/

Also the error does not seem to be related to html (https://www.reddit.com/r/Nexus6P/comments/5x4zlm/there_was_a_problem_parsing_the_package_error/?st=j5enrrb6&sh=b849b958 for example) ..

**Comment by apps4av** [comment]
I don't see this issue either because it's not route related but probably
browser related.

**Comment by pasniak** [comment]
Do you have to sign the apk?   Are there any messages in the log?
Maybe this is related to:
build771

I found this too :
 https://stackoverflow.com/questions/21808188/error-parsing-the-package-while-installing-apk
https://stackoverflow.com/questions/33717104/why-signed-and-released-apk-is-not-installing-to-the-other-devices#

Possibly also the code to write html file should use "text/html" and ShareCompat.IntentBuilder ?

https://stackoverflow.com/questions/18249007/how-to-use-support-fileprovider-for-sharing-content-to-other-apps/18332000#18332000

**Comment by apps4av** [comment]
We are using api 23 so share file intent is not a problem.

**Comment by pasniak** [comment]
Unable to repro the issue here. I uninstalled Avare and got 7.7.1 from Play on Moto G and Moto X (no root on both). Wx Brief works nicely with Chrome, Firefox, Opera.  I also tried dropping apk on Galaxy Nexus emulator (19), no problems there.

**Comment by apps4av** [comment]
OK maybe issue with user phone. Will keep the code.

**Comment by pasniak** [comment]
https://developer.android.com/traning/basics/data-storage/files.html

> Note: Before Android 7.0 (API level 24), internal files could be made accessible to other apps by means of relaxing file system permissions. This is no longer > the case. If you wish to make the content of a private file accessible to other apps, your app may use the FileProvider. See Sharing Files.

well explained: https://github.com/codepath/android_guides/wiki/Sharing-Content-with-Intents

I have 6.0 (23) emulator... this is explained by:
https://github.com/codepath/android_guides/wiki/Managing-Runtime-Permissions-with-PermissionsDispatcher

**Comment by apps4av** [comment]
This file sharing will be used when we upgrade to higher api as target sdk
which will not be any time soon. 6 or 7 regardless are backward compatible.

**Comment by pasniak** [comment]
build.gradle suggests we are targetting (targetSdkVersion) 23

> If the device is running Android 6.0 or higher, and **your app's target SDK is 23** or higher: The app has to list the permissions in the manifest, and **it must request each dangerous permission it needs while the app is running**. The user can grant or deny each permission, and the app can continue to run with limited capabilities even if the user denies a permission request.

https://developer.android.com/training/permissions/requesting.html

**Comment by apps4av** [comment]
Yes but this issue is not about permissions . It's about sharing files with
content provider which is not required in 23.

**Pull request merged**
