### PR TITLE
use the closest (preference-based) METAR for performance calculations…

### PR DESCRIPTION
**Pull request by pasniak**
… and refactor search of the closest coordinates

### CODE REVIEW

**Comment by pasniak** [comment]
second try. I made the default circle of search 5mi.

**Comment by r-oleary** [comment]
@pasniak - is this PR ready to go? Also, are you on slack? I have another idea that I'd like to share with you that is related to this...

**Comment by pasniak** [comment]
I never used slack. Just checked but it cannot find "my team". That seems like an invite only affair....

**Comment by r-oleary** [comment]
You can join the Avare slack here: https://avare-chat.herokuapp.com/

**Comment by pasniak** [comment]
I executed that again and it works as intended.  I run out of ideas of edge cases for testing... so it's RFM.

--------------------------------------------
On Sun, 11/27/16, r-oleary <notifications@github.com> wrote:

 Subject: Re: [apps4av/avare] use the closest (preference-based) METAR for performance calculations… (#247)
 To: "apps4av/avare" <avare@noreply.github.com>
 Cc: "pasniak" <michalp@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Sunday, November 27, 2016, 11:12 AM
 
 @pasniak - is this PR
 ready to go? Also, are you on slack? I have another idea
 that I'd like to share with you that is related to
 this...
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Pull request closed without merging**
