### PR TITLE
Cleanup location view

### PR DESCRIPTION
**Pull request by apps4av**
Moving the pop up for destination to Near and Find. More uniform behavior. Cleanup with get/set. Moved BT IO to #2 so BT issues wont crash the app on fresh install. Caught and fixed busy loop in USBIn IO.

### CODE REVIEW

**Review by N520TX — APPROVED** [review]
Appears mostly to be cleanup of style and object scope access. Did a pull and tested affected areas. Did not test out the USB "bug" changes, no hardware.

**Comment by apps4av** [comment]
Check long press on Find elements (airports, GPS, navaids, addresses) and
Near elements (airports).

**Comment by N520TX** [comment]
Yes - tested that panel. The buttons that display are context sensitive based upon the type of the list select that was long pressed. When this gets merged, this is where I'll hook the "Set DME" functionality in to as well, stack it on top of the "WX" button.

**Comment by apps4av** [comment]
Actually all those context sensitive buttons are gone. Everything and all
buttons are in pop out dialog now with this PR.

**Comment by N520TX** [comment]
I see that now - was in the wrong branch. That pop out dialog on the "find" panel behaves the way the long press did on the chart. Same dialog. Any way to "gray out" or otherwise disable the PLATE and CSUP selections when they are not applicable to the station selected ? Is the red "X" button required given the system "Back" provides same functionality  ?

**Comment by apps4av** [comment]
Noted. If you need more real estate to add buttons, you can use the second row. I will look into disabling other buttons

**Pull request merged**
