### PR TITLE
Auto fit plates

### PR DESCRIPTION
**Pull request by r-oleary**
This PR is based off 'use_native_multitouch', so includes those changes as well.

### CODE REVIEW

**Comment by apps4av** [comment]
This and new touch has issues. Tested on Galaxy S6
- Panning does not work. When you pan, new tiles wont load and black area stays and you are bound to your current location or to simulated destination.
- Swipe is intermittent. Sometimes a few swipes get skipped without a pan.
- Plates dont pan or scale properly in track up mode. Use IO module's GPS sim to test. 

Backing out from trunk.

**Comment by r-oleary** [comment]
Any way to get a screen cap of these behaviors? I'm not really seeing any
of this on my S4 or on my Tab S2, at least not frequently/consistently.

**Comment by r-oleary** [comment]
Nm, I think I can reproduce. Will take a look sometime this week or weekend

**Comment by r-oleary** [comment]
Ok, I can repro #1 and #3.

Can you explain #2 a bit more? Are there repro steps I can use to see that
behavior?

**Comment by apps4av** [comment]
When I swipe quickly left and right, sometimes, for a brief moment the
panning hangs. The hang is like when you do a long running blocking call on
the UI thread.

**Comment by r-oleary** [comment]
OK, and this is in Map view?

**Comment by apps4av** [comment]
Only in map view.

**Comment by r-oleary** [comment]
Can you confirm - on master, when I do an Airport Diagram with "Track Up",
my ship is moving right-to-left across the screen, not "up". Is that right?

**Comment by apps4av** [comment]
Which aorport?

**Comment by r-oleary** [comment]
KSBA.

**Comment by apps4av** [comment]
Yes it does because N for that airport diagram is to left of screen.
On Jun 6, 2016 9:32 PM, "r-oleary" <notifications@github.com> wrote:

KSBA.

On Mon, Jun 6, 2016 at 6:32 PM, Zubair Khan <notifications@github.com>

wrote:

> Which aorport?
>
> On Jun 6, 2016 9:29 PM, "r-oleary" <notifications@github.com> wrote:
>
> > Can you confirm - on master, when I do an Airport Diagram with "Track
> Up",
> > my ship is moving right-to-left across the screen, not "up". Is that
> right?
> >
> > On Mon, Jun 6, 2016 at 4:47 PM, Zubair Khan <notifications@github.com>
> > wrote:
> >
> > > Only in map view.
> > >
> > > On Jun 6, 2016 7:45 PM, "r-oleary" <notifications@github.com> wrote:
> > >
> > > > OK, and this is in Map view?
> > > >
> > > > On Mon, Jun 6, 2016 at 4:45 PM, Zubair Khan <
> notifications@github.com>
> > > > wrote:
> > > >
> > > > > When I swipe quickly left and right, sometimes, for a brief moment
> > the
> > > > > panning hangs. The hang is like when you do a long running
blocking
> > > call
> > > > on
> > > > > the UI thread.
> > > > > On Jun 6, 2016 7:40 PM, "r-oleary" <notifications@github.com>
> wrote:
> > > > >
> > > > > > Ok, I can repro #1 and #3.
> > > > > >
> > > > > > Can you explain #2 a bit more? Are there repro steps I can use
to
> > see
> > > > > that
> > > > > > behavior?
> > > > > >
> > > > > > On Sun, Jun 5, 2016 at 10:12 PM, Ryan O'Leary <roleary@gmail.com
> >
> > > > wrote:
> > > > > >
> > > > > > > Nm, I think I can reproduce. Will take a look sometime this
> week
> > or
> > > > > > weekend
> > > > > > > On Jun 5, 2016 8:10 PM, "Ryan O'Leary" <roleary@gmail.com>
> > wrote:
> > > > > > >
> > > > > > >> Any way to get a screen cap of these behaviors? I'm not
really
> > > > seeing
> > > > > > any
> > > > > > >> of this on my S4 or on my Tab S2, at least not
> > > > > frequently/consistently.
> > > > > > >>
> > > > > > >> On Sun, Jun 5, 2016 at 6:16 PM, Zubair Khan <
> > > > notifications@github.com
> > > > > >
> > > > > > >> wrote:
> > > > > > >>
> > > > > > >>> This and new touch has issues. Tested on Galaxy S6
> > > > > > >>>
> > > > > > >>> - Panning does not work. When you pan, new tiles wont load
> and
> > > > black
> > > > > > >>> area stays and you are bound to your current location or to
> > > > simulated
> > > > > > >>> destination.
> > > > > > >>> - Swipe is intermittent. Sometimes a few swipes get skipped
> > > without
> > > > > > >>> a pan.
> > > > > > >>> - Plates dont pan or scale properly in track up mode. Use IO
> > > > > > >>> module's GPS sim to test.
> > > > > > >>>
> > > > > > >>> Backing out from trunk.
> > > > > > >>>
> > > > > > >>> —
> > > > > > >>> You are receiving this because you authored the thread.
> > > > > > >>> Reply to this email directly, view it on GitHub
> > > > > > >>> <
> > > https://github.com/apps4av/avare/pull/185#issuecomment-223850428
> > > > >,
> > > > > > or mute
> > > > > > >>> the thread
> > > > > > >>> <
> > > > > >
> > > > >
> > > >
> > >
> >
>
https://github.com/notifications/unsubscribe/ABTR3byyagW0pvhIsMc2kc2kveCsTVNpks5qI3UFgaJpZM4IuaK2
> > > > > > >
> > > > > > >>> .
> > > > > > >>>
> > > > > > >>
> > > > > > >>
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you modified the open/close
state.
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> https://github.com/apps4av/avare/pull/185#issuecomment-224121403
> > >,
> > > or
> > > > > mute
> > > > > > the thread
> > > > > > <
> > > > >
> > > >
> > >
> >
>
https://github.com/notifications/unsubscribe/ACz4z8hKFERD6dRTJ0JzlcwpD0Cf68-Jks5qJLAEgaJpZM4IuaK2
> > > > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224122100
> >,
> > or
> > > > mute
> > > > > the thread
> > > > > <
> > > >
> > >
> >
>
https://github.com/notifications/unsubscribe/ABTR3e4y2x1HJ71846_GcdQwuvzuKSskks5qJLELgaJpZM4IuaK2
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224122203>,
> or
> > > mute
> > > > the thread
> > > > <
> > >
> >
>
https://github.com/notifications/unsubscribe/ACz4z4zfcBcrGiSgtHiR9D_PX7gFGcZFks5qJLExgaJpZM4IuaK2
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/185#issuecomment-224122424>, or
> > mute
> > > the thread
> > > <
> >
>
https://github.com/notifications/unsubscribe/ABTR3WsSbFO7BMuiw1Aq2dOLy5uP1QA-ks5qJLGNgaJpZM4IuaK2
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you modified the open/close state.

> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/185#issuecomment-224137134>, or
> mute
> > the thread
> > <
>
https://github.com/notifications/unsubscribe/ACz4z8Y5JVC_D5Pipy65eZY8McdKg9iuks5qJMmQgaJpZM4IuaK2
> >
>
> > .
> >
>
> —
> You are receiving this because you authored the thread.

> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/185#issuecomment-224137466>, or
mute
> the thread
> <
https://github.com/notifications/unsubscribe/ABTR3cDa9hLIOdDLn5jR9_hVxIGEIPvTks5qJMofgaJpZM4IuaK2
>
> .
>

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/apps4av/avare/pull/185#issuecomment-224137552>, or mute
the thread
<https://github.com/notifications/unsubscribe/ACz4z1SUQfojPnbz2E_ai6pIzVhQBTMZks5qJMo_gaJpZM4IuaK2>
.

**Comment by r-oleary** [comment]
I find that quite strange, but ok. I can see it behaving the way I
"expected" it to on other plates, so I'm good. Thanks.

**Comment by apps4av** [comment]
I agree that needs fixing.
Z

On Mon, Jun 6, 2016 at 10:15 PM, r-oleary <notifications@github.com> wrote:

> I find that quite strange, but ok. I can see it behaving the way I
> "expected" it to on other plates, so I'm good. Thanks.
>
> On Mon, Jun 6, 2016 at 6:41 PM, Zubair Khan <notifications@github.com>
> wrote:
>
> > Yes it does because N for that airport diagram is to left of screen.
> >
> > On Jun 6, 2016 9:32 PM, "r-oleary" <notifications@github.com> wrote:
> >
> > KSBA.
> >
> > On Mon, Jun 6, 2016 at 6:32 PM, Zubair Khan <notifications@github.com>
> >
> > wrote:
> >
> > > Which aorport?
> > >
> > > On Jun 6, 2016 9:29 PM, "r-oleary" <notifications@github.com> wrote:
> > >
> > > > Can you confirm - on master, when I do an Airport Diagram with "Track
> > > Up",
> > > > my ship is moving right-to-left across the screen, not "up". Is that
> > > right?
> > > >
> > > > On Mon, Jun 6, 2016 at 4:47 PM, Zubair Khan <
> notifications@github.com>
> > > > wrote:
> > > >
> > > > > Only in map view.
> > > > >
> > > > > On Jun 6, 2016 7:45 PM, "r-oleary" <notifications@github.com>
> wrote:
> > > > >
> > > > > > OK, and this is in Map view?
> > > > > >
> > > > > > On Mon, Jun 6, 2016 at 4:45 PM, Zubair Khan <
> > > notifications@github.com>
> > > > > > wrote:
> > > > > >
> > > > > > > When I swipe quickly left and right, sometimes, for a brief
> > moment
> > > > the
> > > > > > > panning hangs. The hang is like when you do a long running
> > blocking
> > > > > call
> > > > > > on
> > > > > > > the UI thread.
> > > > > > > On Jun 6, 2016 7:40 PM, "r-oleary" <notifications@github.com>
> > > wrote:
> > > > > > >
> > > > > > > > Ok, I can repro #1 and #3.
> > > > > > > >
> > > > > > > > Can you explain #2 a bit more? Are there repro steps I can
> use
> > to
> > > > see
> > > > > > > that
> > > > > > > > behavior?
> > > > > > > >
> > > > > > > > On Sun, Jun 5, 2016 at 10:12 PM, Ryan O'Leary <
> > roleary@gmail.com
> > > >
> > > > > > wrote:
> > > > > > > >
> > > > > > > > > Nm, I think I can reproduce. Will take a look sometime this
> > > week
> > > > or
> > > > > > > > weekend
> > > > > > > > > On Jun 5, 2016 8:10 PM, "Ryan O'Leary" <roleary@gmail.com>
> > > > wrote:
> > > > > > > > >
> > > > > > > > >> Any way to get a screen cap of these behaviors? I'm not
> > really
> > > > > > seeing
> > > > > > > > any
> > > > > > > > >> of this on my S4 or on my Tab S2, at least not
> > > > > > > frequently/consistently.
> > > > > > > > >>
> > > > > > > > >> On Sun, Jun 5, 2016 at 6:16 PM, Zubair Khan <
> > > > > > notifications@github.com
> > > > > > > >
> > > > > > > > >> wrote:
> > > > > > > > >>
> > > > > > > > >>> This and new touch has issues. Tested on Galaxy S6
> > > > > > > > >>>
> > > > > > > > >>> - Panning does not work. When you pan, new tiles wont
> load
> > > and
> > > > > > black
> > > > > > > > >>> area stays and you are bound to your current location or
> to
> > > > > > simulated
> > > > > > > > >>> destination.
> > > > > > > > >>> - Swipe is intermittent. Sometimes a few swipes get
> skipped
> > > > > without
> > > > > > > > >>> a pan.
> > > > > > > > >>> - Plates dont pan or scale properly in track up mode. Use
> > IO
> > > > > > > > >>> module's GPS sim to test.
> > > > > > > > >>>
> > > > > > > > >>> Backing out from trunk.
> > > > > > > > >>>
> > > > > > > > >>> —
> > > > > > > > >>> You are receiving this because you authored the thread.
> > > > > > > > >>> Reply to this email directly, view it on GitHub
> > > > > > > > >>> <
> > > > > https://github.com/apps4av/avare/pull/185#issuecomment-223850428
> > > > > > >,
> > > > > > > > or mute
> > > > > > > > >>> the thread
> > > > > > > > >>> <
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ABTR3byyagW0pvhIsMc2kc2kveCsTVNpks5qI3UFgaJpZM4IuaK2
> > > > > > > > >
> > > > > > > > >>> .
> > > > > > > > >>>
> > > > > > > > >>
> > > > > > > > >>
> > > > > > > >
> > > > > > > > —
> > > > > > > > You are receiving this because you modified the open/close
> > state.
> > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > <
> > > https://github.com/apps4av/avare/pull/185#issuecomment-224121403
> > > > >,
> > > > > or
> > > > > > > mute
> > > > > > > > the thread
> > > > > > > > <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ACz4z8hKFERD6dRTJ0JzlcwpD0Cf68-Jks5qJLAEgaJpZM4IuaK2
> > > > > > > >
> > > > > > >
> > > > > > > > .
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > You are receiving this because you authored the thread.
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <
> > https://github.com/apps4av/avare/pull/185#issuecomment-224122100
> > > >,
> > > > or
> > > > > > mute
> > > > > > > the thread
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ABTR3e4y2x1HJ71846_GcdQwuvzuKSskks5qJLELgaJpZM4IuaK2
> > > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you modified the open/close state.
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> https://github.com/apps4av/avare/pull/185#issuecomment-224122203
> > >,
> > > or
> > > > > mute
> > > > > > the thread
> > > > > > <
> > > > >
> > > >
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ACz4z4zfcBcrGiSgtHiR9D_PX7gFGcZFks5qJLExgaJpZM4IuaK2
> > > > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224122424
> >,
> > or
> > > > mute
> > > > > the thread
> > > > > <
> > > >
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ABTR3WsSbFO7BMuiw1Aq2dOLy5uP1QA-ks5qJLGNgaJpZM4IuaK2
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you modified the open/close state.
> >
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224137134>,
> or
> > > mute
> > > > the thread
> > > > <
> > >
> >
> >
> https://github.com/notifications/unsubscribe/ACz4z8Y5JVC_D5Pipy65eZY8McdKg9iuks5qJMmQgaJpZM4IuaK2
> > > >
> > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you authored the thread.
> >
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/185#issuecomment-224137466>, or
> > mute
> > > the thread
> > > <
> >
> >
> https://github.com/notifications/unsubscribe/ABTR3cDa9hLIOdDLn5jR9_hVxIGEIPvTks5qJMofgaJpZM4IuaK2
> > >
> > > .
> > >
> >
> > —
> > You are receiving this because you modified the open/close state.
> >
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/185#issuecomment-224137552>, or
> > mute
> > the thread
> > <
> >
> https://github.com/notifications/unsubscribe/ACz4z1SUQfojPnbz2E_ai6pIzVhQBTMZks5qJMo_gaJpZM4IuaK2
> > >
> >
> > .
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/185#issuecomment-224138741>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABTR3TvkEMEpzC1oN53xbWvQqowaaKjwks5qJMwugaJpZM4IuaK2
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/185#issuecomment-224146025>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACz4z1rlPCilKTg432UoH1ACCc_HTudoks5qJNQygaJpZM4IuaK2>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by r-oleary** [comment]
Hey Z - can you check this branch out and see if it resolves your issues? I
_think_ I've covered them. Thanks:
https://github.com/r-oleary/avare/tree/multitouch_cleanup

**Comment by apps4av** [comment]
OK lets plan on making a build with it so others can test it before release.
Thanks
Z

On Sat, Jun 11, 2016 at 3:52 PM, r-oleary <notifications@github.com> wrote:

> Hey Z - can you check this branch out and see if it resolves your issues? I
> _think_ I've covered them. Thanks:
> https://github.com/r-oleary/avare/tree/multitouch_cleanup
>
> On Tue, Jun 7, 2016 at 5:29 AM, Zubair Khan <notifications@github.com>
> wrote:
>
> > I agree that needs fixing.
> > Z
> >
> >
> > On Mon, Jun 6, 2016 at 10:15 PM, r-oleary <notifications@github.com>
> > wrote:
> >
> > > I find that quite strange, but ok. I can see it behaving the way I
> > > "expected" it to on other plates, so I'm good. Thanks.
> > >
> > > On Mon, Jun 6, 2016 at 6:41 PM, Zubair Khan <notifications@github.com>
> > > wrote:
> > >
> > > > Yes it does because N for that airport diagram is to left of screen.
> > > >
> > > > On Jun 6, 2016 9:32 PM, "r-oleary" <notifications@github.com> wrote:
> > > >
> > > > KSBA.
> > > >
> > > > On Mon, Jun 6, 2016 at 6:32 PM, Zubair Khan <
> notifications@github.com>
> > > >
> > > > wrote:
> > > >
> > > > > Which aorport?
> > > > >
> > > > > On Jun 6, 2016 9:29 PM, "r-oleary" <notifications@github.com>
> wrote:
> > > > >
> > > > > > Can you confirm - on master, when I do an Airport Diagram with
> > "Track
> > > > > Up",
> > > > > > my ship is moving right-to-left across the screen, not "up". Is
> > that
> > > > > right?
> > > > > >
> > > > > > On Mon, Jun 6, 2016 at 4:47 PM, Zubair Khan <
> > > notifications@github.com>
> > > > > > wrote:
> > > > > >
> > > > > > > Only in map view.
> > > > > > >
> > > > > > > On Jun 6, 2016 7:45 PM, "r-oleary" <notifications@github.com>
> > > wrote:
> > > > > > >
> > > > > > > > OK, and this is in Map view?
> > > > > > > >
> > > > > > > > On Mon, Jun 6, 2016 at 4:45 PM, Zubair Khan <
> > > > > notifications@github.com>
> > > > > > > > wrote:
> > > > > > > >
> > > > > > > > > When I swipe quickly left and right, sometimes, for a brief
> > > > moment
> > > > > > the
> > > > > > > > > panning hangs. The hang is like when you do a long running
> > > > blocking
> > > > > > > call
> > > > > > > > on
> > > > > > > > > the UI thread.
> > > > > > > > > On Jun 6, 2016 7:40 PM, "r-oleary" <
> notifications@github.com
> > >
> > > > > wrote:
> > > > > > > > >
> > > > > > > > > > Ok, I can repro #1 and #3.
> > > > > > > > > >
> > > > > > > > > > Can you explain #2 a bit more? Are there repro steps I
> can
> > > use
> > > > to
> > > > > > see
> > > > > > > > > that
> > > > > > > > > > behavior?
> > > > > > > > > >
> > > > > > > > > > On Sun, Jun 5, 2016 at 10:12 PM, Ryan O'Leary <
> > > > roleary@gmail.com
> > > > > >
> > > > > > > > wrote:
> > > > > > > > > >
> > > > > > > > > > > Nm, I think I can reproduce. Will take a look sometime
> > this
> > > > > week
> > > > > > or
> > > > > > > > > > weekend
> > > > > > > > > > > On Jun 5, 2016 8:10 PM, "Ryan O'Leary" <
> > roleary@gmail.com>
> > > > > > wrote:
> > > > > > > > > > >
> > > > > > > > > > >> Any way to get a screen cap of these behaviors? I'm
> not
> > > > really
> > > > > > > > seeing
> > > > > > > > > > any
> > > > > > > > > > >> of this on my S4 or on my Tab S2, at least not
> > > > > > > > > frequently/consistently.
> > > > > > > > > > >>
> > > > > > > > > > >> On Sun, Jun 5, 2016 at 6:16 PM, Zubair Khan <
> > > > > > > > notifications@github.com
> > > > > > > > > >
> > > > > > > > > > >> wrote:
> > > > > > > > > > >>
> > > > > > > > > > >>> This and new touch has issues. Tested on Galaxy S6
> > > > > > > > > > >>>
> > > > > > > > > > >>> - Panning does not work. When you pan, new tiles wont
> > > load
> > > > > and
> > > > > > > > black
> > > > > > > > > > >>> area stays and you are bound to your current location
> > or
> > > to
> > > > > > > > simulated
> > > > > > > > > > >>> destination.
> > > > > > > > > > >>> - Swipe is intermittent. Sometimes a few swipes get
> > > skipped
> > > > > > > without
> > > > > > > > > > >>> a pan.
> > > > > > > > > > >>> - Plates dont pan or scale properly in track up mode.
> > Use
> > > > IO
> > > > > > > > > > >>> module's GPS sim to test.
> > > > > > > > > > >>>
> > > > > > > > > > >>> Backing out from trunk.
> > > > > > > > > > >>>
> > > > > > > > > > >>> —
> > > > > > > > > > >>> You are receiving this because you authored the
> thread.
> > > > > > > > > > >>> Reply to this email directly, view it on GitHub
> > > > > > > > > > >>> <
> > > > > > >
> https://github.com/apps4av/avare/pull/185#issuecomment-223850428
> > > > > > > > >,
> > > > > > > > > > or mute
> > > > > > > > > > >>> the thread
> > > > > > > > > > >>> <
> > > > > > > > > >
> > > > > > > > >
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ABTR3byyagW0pvhIsMc2kc2kveCsTVNpks5qI3UFgaJpZM4IuaK2
> > > > > > > > > > >
> > > > > > > > > > >>> .
> > > > > > > > > > >>>
> > > > > > > > > > >>
> > > > > > > > > > >>
> > > > > > > > > >
> > > > > > > > > > —
> > > > > > > > > > You are receiving this because you modified the
> open/close
> > > > state.
> > > > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > > > <
> > > > > https://github.com/apps4av/avare/pull/185#issuecomment-224121403
> > > > > > >,
> > > > > > > or
> > > > > > > > > mute
> > > > > > > > > > the thread
> > > > > > > > > > <
> > > > > > > > >
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ACz4z8hKFERD6dRTJ0JzlcwpD0Cf68-Jks5qJLAEgaJpZM4IuaK2
> > > > > > > > > >
> > > > > > > > >
> > > > > > > > > > .
> > > > > > > > > >
> > > > > > > > >
> > > > > > > > > —
> > > > > > > > > You are receiving this because you authored the thread.
> > > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > > <
> > > > https://github.com/apps4av/avare/pull/185#issuecomment-224122100
> > > > > >,
> > > > > > or
> > > > > > > > mute
> > > > > > > > > the thread
> > > > > > > > > <
> > > > > > > >
> > > > > > >
> > > > > >
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ABTR3e4y2x1HJ71846_GcdQwuvzuKSskks5qJLELgaJpZM4IuaK2
> > > > > > > > >
> > > > > > > > > .
> > > > > > > > >
> > > > > > > >
> > > > > > > > —
> > > > > > > > You are receiving this because you modified the open/close
> > state.
> > > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > > <
> > > https://github.com/apps4av/avare/pull/185#issuecomment-224122203
> > > > >,
> > > > > or
> > > > > > > mute
> > > > > > > > the thread
> > > > > > > > <
> > > > > > >
> > > > > >
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ACz4z4zfcBcrGiSgtHiR9D_PX7gFGcZFks5qJLExgaJpZM4IuaK2
> > > > > > > >
> > > > > > >
> > > > > > > > .
> > > > > > > >
> > > > > > >
> > > > > > > —
> > > > > > > You are receiving this because you authored the thread.
> > > > > > > Reply to this email directly, view it on GitHub
> > > > > > > <
> > https://github.com/apps4av/avare/pull/185#issuecomment-224122424
> > > >,
> > > > or
> > > > > > mute
> > > > > > > the thread
> > > > > > > <
> > > > > >
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ABTR3WsSbFO7BMuiw1Aq2dOLy5uP1QA-ks5qJLGNgaJpZM4IuaK2
> > > > > > >
> > > > > > > .
> > > > > > >
> > > > > >
> > > > > > —
> > > > > > You are receiving this because you modified the open/close state.
> > > >
> > > > > > Reply to this email directly, view it on GitHub
> > > > > > <
> https://github.com/apps4av/avare/pull/185#issuecomment-224137134
> > >,
> > > or
> > > > > mute
> > > > > > the thread
> > > > > > <
> > > > >
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ACz4z8Y5JVC_D5Pipy65eZY8McdKg9iuks5qJMmQgaJpZM4IuaK2
> > > > > >
> > > > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > >
> > > > > Reply to this email directly, view it on GitHub
> > > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224137466
> >,
> > or
> > > > mute
> > > > > the thread
> > > > > <
> > > >
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ABTR3cDa9hLIOdDLn5jR9_hVxIGEIPvTks5qJMofgaJpZM4IuaK2
> > > > >
> > > > > .
> > > > >
> > > >
> > > > —
> > > > You are receiving this because you modified the open/close state.
> > > >
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224137552>,
> or
> > > > mute
> > > > the thread
> > > > <
> > > >
> > >
> >
> https://github.com/notifications/unsubscribe/ACz4z1SUQfojPnbz2E_ai6pIzVhQBTMZks5qJMo_gaJpZM4IuaK2
> > > > >
> > > >
> > > > .
> > > >
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/apps4av/avare/pull/185#issuecomment-224138741>,
> or
> > > mute
> > > > the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/ABTR3TvkEMEpzC1oN53xbWvQqowaaKjwks5qJMwugaJpZM4IuaK2
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you modified the open/close state.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/185#issuecomment-224146025>, or
> > mute
> > > the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ACz4z1rlPCilKTg432UoH1ACCc_HTudoks5qJNQygaJpZM4IuaK2
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Zubair Khan
> > apps4av.com
> > zk4u.blogspot.com
> > Sudbury, MA 01776
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/185#issuecomment-224265416>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABTR3aC2RgsofEO6IQgje-Vw4jciykKBks5qJWQ_gaJpZM4IuaK2
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/185#issuecomment-225390714>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACz4z6WScByCylIekptb-hqSDndza_G9ks5qKxIagaJpZM4IuaK2>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by r-oleary** [comment]
Ok, will submit a PR to master later today

**Comment by r-oleary** [comment]
https://github.com/apps4av/avare/pull/188

**Pull request merged**
