### PR TITLE
GC/perf improvements and related Destination tests [take 2]

### PR DESCRIPTION
**Pull request by pasniak**

### CODE REVIEW

**Comment by apps4av** [comment]
merged with fixes

**Comment by apps4av** [comment]
Travis CI is failing the tests. Think thats because the database is
missing.

**Comment by pasniak** [comment]
Hmm, but why would the last commit on pasniak/avare/dest_tests2 (7h ago) pass? Did database.zip got removed as we speak switched to the new cycle?

**Comment by apps4av** [comment]
Well yes because its in a new folder 1705 instead of in 1704. You need to
get version from apps4av.org/new/version.php.

**Comment by pasniak** [comment]
OK, will update the download (test setup) process.

**Comment by pasniak** [comment]
The failure is due to dependencies of test task on assets (fonts in this case).  I do not know how to express this in build.gradle.

Tests pass (see https://travis-ci.org/pasniak/avare/builds/227230783?utm_source=github_status&utm_medium=notification) if I comment out
        //mShadowPaint.setTypeface(Typeface.createFromAsset(context.getAssets(), "LiberationMono-Bold.ttf"));
used in StorageService.class,

Locally, this manifests itself by font not found:

>  Note: if "Font not found at" error occurs this is due to a bug
>  see https://github.com/robolectric/robolectric/issues/2647
>  and https://issuetracker.google.com/issues/37347564
>  A temporary workaround is to add task dependency on mergeDebugAssets
>  in Run/Debug Configurations (see https://i.imgur.com/u6KSxQq.png)

**Comment by pasniak** [comment]
I tested ETA calc in my car (the master branch) and it was not refreshing properly (reopening Avare made it how correct ae. We probably need to go back to recreating new calendar on refresh.

**Pull request merged**
