### PR TITLE
TrackUp Plates !

### PR DESCRIPTION
**Pull request by patricius972**

### CODE REVIEW

**Comment by apps4av** [comment]
There are bugs in this implementation:
1. The plate is moving with the air plane, this can be seen if looked carefully with plate, but very obvious with airport diagram or area plate because of their scale
2. Its rotating the plates that are not geo tagged
3. Zoom and Pan are intermittent
4. Shaded Info lines are rotated with the plate. They should stay on top like they stay on top on Map
Rejecting till fixed. Thanks

**Comment by apps4av** [comment]
Testing should be performed with Area plate and airport diagram to pass.

**Comment by apps4av** [comment]
And test with Avare External IO module with GPS Sim and Fly to Destination.

**Comment by apps4av** [comment]
Note that in map view, map moves and plane stays at center. In plate view, plane moves, and plate stays where it is.

**Comment by apps4av** [comment]
I have removed zoom on center to be consistent with Map screen center. So only issue (1) remains with "Note that in map view, map moves and plane stays at center. In plate view, plane moves, and plate stays where it is."

**Comment by patricius972** [comment]
Ok thanks for the fixes. To fix the map moving, try to replace the canvas.rotate instead of rotating on the pixx and pixy , rotate with the center of the plate (0,0) ?

**Comment by apps4av** [comment]
Are you trying that?
Thanks


On Fri, Aug 28, 2015 at 11:24 AM, patricius972 <notifications@github.com>
wrote:

> Ok thanks for the fixes. To fix the map moving, try to replace the
> canvas.rotate instead of rotating on the pixx and pixy , rotate with the
> center of the plate (0,0) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apps4av/avare/pull/161#issuecomment-135805604>.
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Pull request merged**
