### PR TITLE
KML 2.2 support

### PR DESCRIPTION
**Pull request by annerajb**
added kml 2.2 this allows avare kml files to be loaded in google maps and show a flight path.

### CODE REVIEW

**Comment by apps4av** [comment]
Can you please remove Logging to adb. We have a no log policy :)

**Comment by annerajb** [comment]
Not sure if when I commit you get a notification or if i have to write a comment to send it to you.
Fixed.

**Comment by apps4av** [comment]
I get it when you comment. Thanks!

**Comment by annerajb** [comment]
Ill open this up again after I fix my branch..

**Pull request closed without merging**
