### PR TITLE
Added waypoint ID to "Delete Waypoint" dialog.

### PR DESCRIPTION
**Pull request by vancinad**
When deleting a waypoint from a flight plan, the dialog did not positively indicate which waypoint was being deleted. I modified the prompt to say "Delete waypoint XYZ?", instead of just "Delete waypoint?"

### CODE REVIEW

**Comment by apps4av** [comment]
Please attach picture of what this will do.

**Comment by vancinad** [comment]
Avare_git359_delete_waypoint_

**Comment by vancinad** [comment]
Should I just close this pull request?

**Review by apps4av — APPROVED** [review]

**Comment by apps4av** [comment]
Its approved. You may merge it.

**Comment by vancinad** [comment]
Great! Thanks. 
Is there doc for how to complete the merge? I haven't done one before.
 
 
  On Sat, Mar 19, 2022 at 3:55 PM, Zubair ***@***.***> wrote:   


Its approved. You may merge it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
