### PR TITLE
CAP Grids: Rev 0.1

### PR DESCRIPTION
**Pull request by postalservice14**
I wanted to start the PR for people to review.

If people could start reviewing and let me know what they think, I'd appreciate it.

Thanks!

This is for the enhancement: https://github.com/apps4av/avare/issues/105

### CODE REVIEW

**Comment by apps4av** [comment]
Will try the solution, but reading the code, I have these comments:

- The cap grid toggle should be placed in Preferences under Display. There
is no space left on the right side slide out buttons (check on LDPI devices)
- Unless if I am missing something, async task to fetch charts is not
needed. Since there is a fixed pool of async tasks, this may hang and slow
down other async tasks. I do not see any disk or net operations in this
asyn task so not needed in my opinion.
- LatLng can be deleted and instead Coordinate class in the code can be
reused.

Thanks!

On Wed, May 13, 2015 at 12:51 AM, John Kelly <notifications@github.com>
wrote:

> I wanted to start the PR for people to review. Currently only SEA area is
> available (I'll add the other charts soon).
>
> If people could start reviewing and let me know what they think, I'd
> appreciate it.
>
> Thanks!
>
> This is for the enhancement: #105
> <https://github.com/apps4av/avare/issues/105>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apps4av/avare/pull/131
> Commit Summary
>
>    - Initial Commit
>    - Initial Commit
>    - Progress check
>    - Merge branch 'master' into cap_grids
>    - no message
>    - Merged but still not working
>    - Merge branch 'master' of https://github.com/apps4av/avare into
>    cap_grids
>    - Big improvements. Only SEA right now
>    - Fix text zoom issue
>
> File Changes
>
>    - *M* project.properties
>    <https://github.com/apps4av/avare/pull/131/files#diff-0> (2)
>    - *M* res/layout/location.xml
>    <https://github.com/apps4av/avare/pull/131/files#diff-1> (14)
>    - *M* res/values/strings.xml
>    <https://github.com/apps4av/avare/pull/131/files#diff-2> (2)
>    - *M* src/com/ds/avare/LocationActivity.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-3> (18)
>    - *M* src/com/ds/avare/StorageService.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-4> (21)
>    - *A* src/com/ds/avare/cap/Boundaries.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-5> (70)
>    - *A* src/com/ds/avare/cap/CapChartFetcher.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-6> (43)
>    - *A* src/com/ds/avare/cap/Chart.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-7> (62)
>    - *A* src/com/ds/avare/cap/ChartIdentifier.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-8> (5)
>    - *A* src/com/ds/avare/cap/CoordinateAwareInterface.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-9> (6)
>    - *A* src/com/ds/avare/cap/Grid.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-10> (64)
>    - *A* src/com/ds/avare/cap/LatLng.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-11> (27)
>    - *A* src/com/ds/avare/shapes/CAPGridShape.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-12> (9)
>    - *M* src/com/ds/avare/views/LocationView.java
>    <https://github.com/apps4av/avare/pull/131/files#diff-13> (47)
>
> Patch Links:
>
>    - https://github.com/apps4av/avare/pull/131.patch
>    - https://github.com/apps4av/avare/pull/131.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apps4av/avare/pull/131>.
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by postalservice14** [comment]
@apps4av, I've implemented your review comments.  I also added the rest of the CAP Grid charts.

**Comment by apps4av** [comment]
Tried this solution further and found it too expensive.
- If you precalculate grids then we run out of memory
- If you calculate girds on the fly, then we slow down a bunch (current solution by postalservice14)

This needs to be done trough sqlite database so girds can be retrived on the fly with SQL queries.

I will take this code, and run it to generate all grids and put them in sqlite database.

**Comment by postalservice14** [comment]
Thanks @apps4av .  Sorry, my time has been very limited recently.  Glad you were able to take it on...

**Comment by apps4av** [comment]
Thank you for the initiative! Please do test it in the latest checked in code as I am not a CAP pilot and you can better judge the correctness of operation. -Z

**Comment by postalservice14** [comment]
Certainly.  At first glance it looks great, but I'll continue to mess with it.

**Pull request closed without merging**
