### PR TITLE
Replace usbseriallibrary.jar with the corresponding java source code

### PR DESCRIPTION
**Pull request by ninelima**
https://github.com/mik3y/usb-serial-for-android.git   

Revision: 2bdcbfd16e644f6e26b9fd74d5bdb3766e324cad  
Author: Felix Hädicke <felixhaedicke@web.de>  
Date: 2013-05-22 06:15:36  
Message:  
Device support: PL2303.

### CODE REVIEW

**Review by apps4av — COMMENTED** [review]
Why not include the code directly from the source location:
https://github.com/mik3y/usb-serial-for-android
For example under Quick Start, code can be imported at build time.

**Comment by ninelima** [comment]
I have never done that before.  Let me see what I can do.

**Comment by ninelima** [comment]
Also the jar file that is used in AVARE corresponds to that exact commit:  2bdcbfd16e644f6e26b9fd74d5bdb3766e324cad
It is quite old, and  it may be a appropriate to have a copy of the code in case someone wants to edit it?

**Comment by apps4av** [comment]
This PR can be closed as the commit https://github.com/apps4av/avare/commit/5b166614252e59bafc0a6696ef4288b012da6461 handles it in a standard way. Thanks for the suggestion.

**Comment by ninelima** [comment]
That is a much better solution.

**Pull request closed without merging**
