### PR TITLE
Draw TFR and Met shapes only when showing on screen

### PR DESCRIPTION
**Pull request by patricius972**

### CODE REVIEW

**Comment by apps4av** [comment]
How much is the CPU saved? Do you see any increase in pan speed when TFRs are showing?
I tried this once and saw that if() block check was slower than drawing the line itself. Plus the worst case remains the same, because users can zoom out to see everything. Thanks!

**Comment by patricius972** [comment]
The if here is at the shape level not the coordinate level, so there is only approx 120 shapes to check, compare to 20+ times that if you do it at the with the shape coordinates. Plus there no computation , the check is done with lon lat which alleviate the call to longitudeoffset of epsg class, all the data need is already computed in the shape or origin. So this is very fast when no or little TFR/Sigmet are showing.  
Yes pan speed increased when little TFR are showing on the view, plus since you need to zoom out to show almost all of them, pan is fast too. I didn't see any slow down and the drawTFR and drawSigmet dropped in the profiling usage I've done.

**Comment by apps4av** [comment]
OK. Please move the common code to base class "Shape.java" because it seems replicated across METAR and TFR classes. Also, please add comments in the code of how this is done for reference of future developers. Thanks.

**Comment by patricius972** [comment]
Done ! Definitely it is faster by a factor of almost 1.5.

**Pull request merged**
