### PR TITLE
Use native multitouch

### PR DESCRIPTION
**Pull request by r-oleary**

### CODE REVIEW

**Comment by apps4av** [comment]
There is a two finger touch code that is gone. It measures distance between
two points in map mode. Its associated with mProjection parameter. Also
worth reviewing code to see what else was accidentally removed.
The scale and pan still hangs for a second some times. There are no
reproducible step, but if you pan/zoom fast in combination, some pan/scale
will be skipped.


On Sun, Jun 12, 2016 at 4:26 PM, r-oleary <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apps4av/avare/pull/188
> Commit Summary
>
>    - Fix rotation panning on PlatesView
>    - Attempt to fix up scaling and tile loading
>    - Revert "reverted new touch"
>    - Revert "last commit before backout."
>    - Merge branch 'use_native_multitouch_fixed' into use_native_multitouch
>
> File Changes
>
>    - *M* app/src/main/java/com/ds/avare/LocationActivity.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-0> (6)
>    - *M* app/src/main/java/com/ds/avare/PlatesActivity.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-1> (10)
>    - *M* app/src/main/java/com/ds/avare/threed/Constants.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-2> (3)
>    - *A*
>    app/src/main/java/com/ds/avare/touch/BasicOnScaleGestureListener.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-3> (64)
>    - *A* app/src/main/java/com/ds/avare/utils/ViewParams.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-4> (69)
>    - *M* app/src/main/java/com/ds/avare/views/AfdView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-5> (135)
>    - *M* app/src/main/java/com/ds/avare/views/LocationView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-6> (320)
>    - *M* app/src/main/java/com/ds/avare/views/PlatesTagView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-7> (139)
>    - *M* app/src/main/java/com/ds/avare/views/PlatesView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-8> (237)
>    - *M* app/src/main/java/com/ds/avare/views/ThreeDSurfaceView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-9> (110)
>    - *D*
>    app/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-10> (852)
>    - *M* build.gradle
>    <https://github.com/apps4av/avare/pull/188/files#diff-11> (2)
>    - *M* gradle/wrapper/gradle-wrapper.properties
>    <https://github.com/apps4av/avare/pull/188/files#diff-12> (12)
>
> Patch Links:
>
>    - https://github.com/apps4av/avare/pull/188.patch
>    - https://github.com/apps4av/avare/pull/188.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/188>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACz4zxDgAixrU55ZIbdyXQLGi2gP7vmFks5qLGuGgaJpZM4Iz4C3>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by r-oleary** [comment]
Interesting on the gesture you mentioned - I didn't realize that feature
(there are a lot of features that are hard to find). I'll take a look at it.

I wasn't able to repro that one issue, at least not consistently. It may be
related to the way tiles are updated and update jobs get canceled/skipped.
I dug into that code for a while and it's very complex - which led to my
question about trying to refactor the whole thing to use google maps API
natively. Is the behavior bad enough to prevent this merge from happening?

Also, is there any way for you to test these things without merging to
master? When you merge and then revert, it makes it quite a pain to get a
new PR to you with all the new code.

**Comment by apps4av** [comment]
OK. This time the merge is final. You will get to change the master after a
little more code familiarization so this wont be an issue.  I think its
working fine except for a few issues as I mention. Note, this was
definitely a very big change to code. Unlike iPhone we have to deal with
thousands of phones and OS versions. Older touch was tested for several
years by thousands of people and worked pretty nice. I wont be surprised if
many people will complain about the new touch for a very long time so be
prepared :)



On Tue, Jun 14, 2016 at 12:40 PM, r-oleary <notifications@github.com> wrote:

> Interesting on the gesture you mentioned - I didn't realize that feature
> (there are a lot of features that are hard to find). I'll take a look at
> it.
>
> I wasn't able to repro that one issue, at least not consistently. It may be
> related to the way tiles are updated and update jobs get canceled/skipped.
> I dug into that code for a while and it's very complex - which led to my
> question about trying to refactor the whole thing to use google maps API
> natively. Is the behavior bad enough to prevent this merge from happening?
>
> Also, is there any way for you to test these things without merging to
> master? When you merge and then revert, it makes it quite a pain to get a
> new PR to you with all the new code.
>
> On Tue, Jun 14, 2016 at 9:04 AM, Zubair Khan <notifications@github.com>
> wrote:
>
> > There is a two finger touch code that is gone. It measures distance
> between
> > two points in map mode. Its associated with mProjection parameter. Also
> > worth reviewing code to see what else was accidentally removed.
> > The scale and pan still hangs for a second some times. There are no
> > reproducible step, but if you pan/zoom fast in combination, some
> pan/scale
> > will be skipped.
> >
> >
> > On Sun, Jun 12, 2016 at 4:26 PM, r-oleary <notifications@github.com>
> > wrote:
> >
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/apps4av/avare/pull/188
> > > Commit Summary
> > >
> > > - Fix rotation panning on PlatesView
> > > - Attempt to fix up scaling and tile loading
> > > - Revert "reverted new touch"
> > > - Revert "last commit before backout."
> > > - Merge branch 'use_native_multitouch_fixed' into use_native_multitouch
> > >
> > > File Changes
> > >
> > > - *M* app/src/main/java/com/ds/avare/LocationActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-0> (6)
> > > - *M* app/src/main/java/com/ds/avare/PlatesActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-1> (10)
> > > - *M* app/src/main/java/com/ds/avare/threed/Constants.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-2> (3)
> > > - *A*
> > > app/src/main/java/com/ds/avare/touch/BasicOnScaleGestureListener.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-3> (64)
> > > - *A* app/src/main/java/com/ds/avare/utils/ViewParams.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-4> (69)
> > > - *M* app/src/main/java/com/ds/avare/views/AfdView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-5> (135)
> > > - *M* app/src/main/java/com/ds/avare/views/LocationView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-6> (320)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesTagView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-7> (139)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-8> (237)
> > > - *M* app/src/main/java/com/ds/avare/views/ThreeDSurfaceView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-9> (110)
> > > - *D*
> > >
> >
> app/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-10> (852)
> > > - *M* build.gradle
> > > <https://github.com/apps4av/avare/pull/188/files#diff-11> (2)
> > > - *M* gradle/wrapper/gradle-wrapper.properties
> > > <https://github.com/apps4av/avare/pull/188/files#diff-12> (12)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/apps4av/avare/pull/188.patch
> > > - https://github.com/apps4av/avare/pull/188.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/188>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ACz4zxDgAixrU55ZIbdyXQLGi2gP7vmFks5qLGuGgaJpZM4Iz4C3
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Zubair Khan
> > apps4av.com
> > zk4u.blogspot.com
> > Sudbury, MA 01776
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/188#issuecomment-225930687>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABTR3etL3roNIApBrD8qkqTth_x-airoks5qLtEkgaJpZM4Iz4C3
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/188#issuecomment-225941260>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACz4z-GKfUYFTj0W3UnzbrVqN3Rog03qks5qLtmQgaJpZM4Iz4C3>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by apps4av** [comment]
Our draw is much faster than google maps and we are not tied to anything.
The code is complex indeed but its mostly due to optimizations in loading.

On Tue, Jun 14, 2016 at 12:40 PM, r-oleary <notifications@github.com> wrote:

> Interesting on the gesture you mentioned - I didn't realize that feature
> (there are a lot of features that are hard to find). I'll take a look at
> it.
>
> I wasn't able to repro that one issue, at least not consistently. It may be
> related to the way tiles are updated and update jobs get canceled/skipped.
> I dug into that code for a while and it's very complex - which led to my
> question about trying to refactor the whole thing to use google maps API
> natively. Is the behavior bad enough to prevent this merge from happening?
>
> Also, is there any way for you to test these things without merging to
> master? When you merge and then revert, it makes it quite a pain to get a
> new PR to you with all the new code.
>
> On Tue, Jun 14, 2016 at 9:04 AM, Zubair Khan <notifications@github.com>
> wrote:
>
> > There is a two finger touch code that is gone. It measures distance
> between
> > two points in map mode. Its associated with mProjection parameter. Also
> > worth reviewing code to see what else was accidentally removed.
> > The scale and pan still hangs for a second some times. There are no
> > reproducible step, but if you pan/zoom fast in combination, some
> pan/scale
> > will be skipped.
> >
> >
> > On Sun, Jun 12, 2016 at 4:26 PM, r-oleary <notifications@github.com>
> > wrote:
> >
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/apps4av/avare/pull/188
> > > Commit Summary
> > >
> > > - Fix rotation panning on PlatesView
> > > - Attempt to fix up scaling and tile loading
> > > - Revert "reverted new touch"
> > > - Revert "last commit before backout."
> > > - Merge branch 'use_native_multitouch_fixed' into use_native_multitouch
> > >
> > > File Changes
> > >
> > > - *M* app/src/main/java/com/ds/avare/LocationActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-0> (6)
> > > - *M* app/src/main/java/com/ds/avare/PlatesActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-1> (10)
> > > - *M* app/src/main/java/com/ds/avare/threed/Constants.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-2> (3)
> > > - *A*
> > > app/src/main/java/com/ds/avare/touch/BasicOnScaleGestureListener.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-3> (64)
> > > - *A* app/src/main/java/com/ds/avare/utils/ViewParams.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-4> (69)
> > > - *M* app/src/main/java/com/ds/avare/views/AfdView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-5> (135)
> > > - *M* app/src/main/java/com/ds/avare/views/LocationView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-6> (320)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesTagView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-7> (139)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-8> (237)
> > > - *M* app/src/main/java/com/ds/avare/views/ThreeDSurfaceView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-9> (110)
> > > - *D*
> > >
> >
> app/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-10> (852)
> > > - *M* build.gradle
> > > <https://github.com/apps4av/avare/pull/188/files#diff-11> (2)
> > > - *M* gradle/wrapper/gradle-wrapper.properties
> > > <https://github.com/apps4av/avare/pull/188/files#diff-12> (12)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/apps4av/avare/pull/188.patch
> > > - https://github.com/apps4av/avare/pull/188.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/188>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ACz4zxDgAixrU55ZIbdyXQLGi2gP7vmFks5qLGuGgaJpZM4Iz4C3
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Zubair Khan
> > apps4av.com
> > zk4u.blogspot.com
> > Sudbury, MA 01776
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/188#issuecomment-225930687>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABTR3etL3roNIApBrD8qkqTth_x-airoks5qLtEkgaJpZM4Iz4C3
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/188#issuecomment-225941260>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACz4z-GKfUYFTj0W3UnzbrVqN3Rog03qks5qLtmQgaJpZM4Iz4C3>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by apps4av** [comment]
Rubber banding is also broken. I will once again back out. Next time lets
merge after it is completely tested.
Thanks
Z

On Sun, Jun 12, 2016 at 4:26 PM, r-oleary <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apps4av/avare/pull/188
> Commit Summary
>
>    - Fix rotation panning on PlatesView
>    - Attempt to fix up scaling and tile loading
>    - Revert "reverted new touch"
>    - Revert "last commit before backout."
>    - Merge branch 'use_native_multitouch_fixed' into use_native_multitouch
>
> File Changes
>
>    - *M* app/src/main/java/com/ds/avare/LocationActivity.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-0> (6)
>    - *M* app/src/main/java/com/ds/avare/PlatesActivity.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-1> (10)
>    - *M* app/src/main/java/com/ds/avare/threed/Constants.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-2> (3)
>    - *A*
>    app/src/main/java/com/ds/avare/touch/BasicOnScaleGestureListener.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-3> (64)
>    - *A* app/src/main/java/com/ds/avare/utils/ViewParams.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-4> (69)
>    - *M* app/src/main/java/com/ds/avare/views/AfdView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-5> (135)
>    - *M* app/src/main/java/com/ds/avare/views/LocationView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-6> (320)
>    - *M* app/src/main/java/com/ds/avare/views/PlatesTagView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-7> (139)
>    - *M* app/src/main/java/com/ds/avare/views/PlatesView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-8> (237)
>    - *M* app/src/main/java/com/ds/avare/views/ThreeDSurfaceView.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-9> (110)
>    - *D*
>    app/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java
>    <https://github.com/apps4av/avare/pull/188/files#diff-10> (852)
>    - *M* build.gradle
>    <https://github.com/apps4av/avare/pull/188/files#diff-11> (2)
>    - *M* gradle/wrapper/gradle-wrapper.properties
>    <https://github.com/apps4av/avare/pull/188/files#diff-12> (12)
>
> Patch Links:
>
>    - https://github.com/apps4av/avare/pull/188.patch
>    - https://github.com/apps4av/avare/pull/188.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/188>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACz4zxDgAixrU55ZIbdyXQLGi2gP7vmFks5qLGuGgaJpZM4Iz4C3>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by r-oleary** [comment]
Yes, I assume there's no official test suite I can run? Do you have any
manual test docs?

**Comment by apps4av** [comment]
Wish we had a QA dept. But not defending our sloppiness. No we do not have
a test report and we rely on users to report  issues. Mostly its defensive
coding. I suggest in order to make this new touch work, you make a class
that works and duplicates API the same as the MultiTouchController class
but has native touch inside. This way all you have to worry about is the
class itself and rest of the features will work.

On Tue, Jun 14, 2016 at 9:54 PM, r-oleary <notifications@github.com> wrote:

> Yes, I assume there's no official test suite I can run? Do you have any
> manual test docs?
> On Jun 14, 2016 6:43 PM, "Zubair Khan" <notifications@github.com> wrote:
>
> > Rubber banding is also broken. I will once again back out. Next time lets
> > merge after it is completely tested.
> > Thanks
> > Z
> >
> > On Sun, Jun 12, 2016 at 4:26 PM, r-oleary <notifications@github.com>
> > wrote:
> >
> > > ------------------------------
> > > You can view, comment on, or merge this pull request online at:
> > >
> > > https://github.com/apps4av/avare/pull/188
> > > Commit Summary
> > >
> > > - Fix rotation panning on PlatesView
> > > - Attempt to fix up scaling and tile loading
> > > - Revert "reverted new touch"
> > > - Revert "last commit before backout."
> > > - Merge branch 'use_native_multitouch_fixed' into use_native_multitouch
> > >
> > > File Changes
> > >
> > > - *M* app/src/main/java/com/ds/avare/LocationActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-0> (6)
> > > - *M* app/src/main/java/com/ds/avare/PlatesActivity.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-1> (10)
> > > - *M* app/src/main/java/com/ds/avare/threed/Constants.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-2> (3)
> > > - *A*
> > > app/src/main/java/com/ds/avare/touch/BasicOnScaleGestureListener.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-3> (64)
> > > - *A* app/src/main/java/com/ds/avare/utils/ViewParams.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-4> (69)
> > > - *M* app/src/main/java/com/ds/avare/views/AfdView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-5> (135)
> > > - *M* app/src/main/java/com/ds/avare/views/LocationView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-6> (320)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesTagView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-7> (139)
> > > - *M* app/src/main/java/com/ds/avare/views/PlatesView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-8> (237)
> > > - *M* app/src/main/java/com/ds/avare/views/ThreeDSurfaceView.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-9> (110)
> > > - *D*
> > >
> >
> app/src/main/java/org/metalev/multitouch/controller/MultiTouchController.java
> > > <https://github.com/apps4av/avare/pull/188/files#diff-10> (852)
> > > - *M* build.gradle
> > > <https://github.com/apps4av/avare/pull/188/files#diff-11> (2)
> > > - *M* gradle/wrapper/gradle-wrapper.properties
> > > <https://github.com/apps4av/avare/pull/188/files#diff-12> (12)
> > >
> > > Patch Links:
> > >
> > > - https://github.com/apps4av/avare/pull/188.patch
> > > - https://github.com/apps4av/avare/pull/188.diff
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <https://github.com/apps4av/avare/pull/188>, or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ACz4zxDgAixrU55ZIbdyXQLGi2gP7vmFks5qLGuGgaJpZM4Iz4C3
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Zubair Khan
> > apps4av.com
> > zk4u.blogspot.com
> > Sudbury, MA 01776
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/apps4av/avare/pull/188#issuecomment-226066130>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/ABTR3cIE_OeMgJZNELi4iFBQ0byvAnzGks5qL1i2gaJpZM4Iz4C3
> >
> > .
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/apps4av/avare/pull/188#issuecomment-226067557>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACz4z9ZdUAbvrpZ8P4UbLog5U38EAGYsks5qL1ttgaJpZM4Iz4C3>
> .
>



-- 
Zubair Khan
apps4av.com
zk4u.blogspot.com
Sudbury, MA 01776

**Comment by r-oleary** [comment]
Fixed the rubber-banding. I see the distance code too, but need some time
to integrate it. I think trying to fit this in the old API would be a major
problem, so will just get these features into it. Do you know off hand of
any other touch interactions? Long-press seems to work fine.

**Comment by r-oleary** [comment]
FYI - got the Projection in there now too. Branch is here if you want to
check it out before merging. I need to clean it up first anyway:
https://github.com/r-oleary/avare/tree/use_native_multitouch

**Pull request merged**
