### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by BradWalker**
Performance improvements
    1 - it's always better to call the System.arraycopy() function. This lets the system use
    a platform specific optimized routine to make a copy

    2 - No need to create an object and then just throw it away. When one can just simply
    call the static function directly. Makes the following code faster and cleaner..
    -               String temp = new Integer(runwayNumber).toString();
   +               String temp = Integer.toString(runwayNumber);

    3 - When adding a bunch of items to a Collection, let the system optimize this by using the
    addAll() method.

### CODE REVIEW

**Comment by BradWalker** [comment]
rebased to the latest code base..

**Comment by BradWalker** [comment]
There is no desire from the Avare team to be proactive w/ minor changes. Therefore, closing this pull request as it will never get integrated.

**Comment by reddn** [comment]
The lack of an active maintainer is stifling development...

**Comment by apps4av** [comment]
It's not that. When app stability is the primary goal you don't take low
value features.

**Comment by BradWalker** [comment]
> It's not that. When app stability is the primary goal you don't take low value features.

I'm not sure that I would call this "low value".. I would call it attention to detail. Or a  better way to look at it is a low-risk change. Which is what I tried to make it.

But, I think the point is that it's unlikely that any change I would propose will get integrated in..

How about change #425 ?

**Comment by reddn** [comment]
Maybe have 2 branches, or 3 to test these features. Also after re-reading
it, I came off wrong.  I forgot to preface it as 'could stifle
development'.

Either way, there needs to be a test bed to test these features, probably
in an automated way as there is no conversation between pull requests and
the maintainer(s) to talk about issues that may have risen.  Its just a
bunch of pull requests just sitting there.  Although I dont have any direct
contribution, or time to do so, if people have a small change and it gets
merged, they will (mostly) want to do more since they are making a
difference, and they are building a history of open source merged pull
requests.  Some employers like to see some software dev candidates with
open source pull request merges so they can see their coding style.

**Comment by apps4av** [comment]
I can tell you why your changes are not taken. Your changes are mostly auto
fill by the tool and there is no value in touching dozens of files.

Performance changes are always dangerous as there are hundreds of devices
where such change will cause undesired effect. We did not see any
performance improvement on our devices.

Please note that we are not obliged to take any of your changes and
volunteering is a way to improve your own coding skills.

**Comment by n251ea** [comment]
Can I propose that I/we setup a private mailing list for use by those 
that want to develop/improve/submit changes for Avare?

Send me a direct email and I'll add you to the mailing list hosted on my 
server.

Jeff

**Comment by apps4av** [comment]
If you send something of value and it's well tested it will be merged.
People have contributed thousands of lines before and developed trust. Once
you develop trust your work will be accepted with less resistance.

**Comment by avcomware** [comment]
Hi Brad and everyone.I proposed to you to compile your version and give it to me / us for testing but you insist on wanting to affect everyone and possibly create problems that the users do not need. 
There is nothing of Real value in what you propose just additional superficial load for everyone. TV

    On Saturday, June 26, 2021, 2:10:37 PM PDT, Brad Walker ***@***.***> wrote:  
 
 



It's not that. When app stability is the primary goal you don't take low value features.


I'm not sure that I would call this "low value".. I would call it attention to detail. Or a better way to look at it is a low-risk change. Which is what I tried to make it.

But, I think the point is that it's unlikely that any change I would propose will get integrated in..

How about change #425 ?

**Comment by reddn** [comment]
Isn't that the purpose of github and it's pull request comments section?

**Comment by BradWalker** [comment]
> if people have a small change and it gets merged, they will (mostly) want to do more since they are making a difference, and they are building a history of open source merged pull requests.

That was completely my intent! My professional opinion is that I like to see small, manageable changes before any Flag Day changes happen.

And @apps4av  says
> Please note that we are not obliged to take any of your changes and volunteering is a way to improve your own coding skills.

I completely understand this. It is your sandbox and you can do as you wish. That's why I closed the pull request as it wasn't going to "go anywhere" and it looks poorly for it to just linger out there.. I was simply doing digital housekeeping as I would do in my professional life. 

At the end of the day, all I'm trying to do is help here.

But understand, things are going to get more stringent going forward. For example, the Google Play store is going to require moving to the Android 11 API in order for any apps to be on it. One of the big changes in Android 11 is location services and that could affect Avare. Just as it has happened in the past with scoped storage.. BTW, there are additional scoped storage changes coming that are more stringent.

I'm certainly happy to continue contributing. But, the team has to tell me the process so that I can follow it. And hopefully get my changes integrated.

**Comment by BradWalker** [comment]
> If you send something of value and it's well tested it will be merged. People have contributed thousands of lines before and developed trust. Once you develop trust your work will be accepted with less resistance.

And that was the whole purpose of such a small change.. To start the process of developing trust.

**Pull request closed without merging**
