### PR TITLE
GC/perf improvements and related Destination tests

### PR DESCRIPTION
**Pull request by pasniak**

### CODE REVIEW

**Comment by apps4av** [comment]
This can be merged but please remove calendar changes.

**Comment by pasniak** [comment]
What's the problem with using single calendar? (1) it is a big object which get recreated (in getInstance call) on every display refresh increasing GC; (2) having single static Calendar makes tests easier as it can be mocked (freezing time, for time calculations)

**Comment by apps4av** [comment]
There is no problem using calendar instance but you should separate out
tests from code. When you send a pull request, and it has bugs, it will be
backed out completely and you lose good code with it. For example for this
PR is calendar causes unforseen issues a complete backout will also back
out your tests. Submit changes separately for better tracking and
management.

Regarding static calender, make it a singleton and code is not acceptable
as is. Statics thrown out in code is bad. Thanks for your help.

**Comment by pasniak** [comment]
The thing is... The tests will not work without a static calendar. I mock the calendar to make ETA testable.. I could add a calendar wrapper singleton, would that work?

**Pull request closed without merging**
